//
//  SHPConstants.h
//  Shopper
//
//  Created by andrea sponziello on 19/08/12.
//
//

#import <Foundation/Foundation.h>

extern NSInteger SHPCONST_MAIN_LIST_TAG_IMAGE;
extern NSString *SHPCONST_MAIN_LIST_NAME;

extern NSString *SHPCONST_MAIN_LIST_GROUPON_CELL_PRICE_ID;
extern NSString *SHPCONST_MAIN_LIST_GROUPON_CELL_PRICE_FULL_ID;
extern NSString *SHPCONST_MAIN_LIST_GROUPON_CELL_LIKE_ID;
extern NSString *SHPCONST_MAIN_LIST_FANCY_CELL_ID;
extern NSString *SHPCONST_MAIN_LIST_PRODUCT_CELL_ID;
extern NSString *SHPCONST_MAIN_LIST_PRODUCT_LAST_CELL_ID;
extern NSString *SHPCONST_GRID_CELL_ID;

extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_CELL_HEIGHT;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_mainCellTopPad;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_mainCellBottomPad;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_mainCellImagePanelDistance;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_mainCellInnerTopPad;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_mainCellInnerBottomPad;
extern float SHPCONST_MAIN_LIST_PRODUCT_panelHeight;
extern float SHPCONST_MAIN_LIST_DESCRIPTION_WIDTH;

extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_DESCRIPTION_LABEL_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_SHOP_LABEL_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_DISTANCE_LABEL_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_BUTTON_LIKE;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_BUTTON_COMMENTS_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_BACK_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_IMAGE_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_BOTTOM_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_LIKESCOUNT_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_USERIMAGE_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_USERNAME_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_CITY_VIEW_TAG;
extern NSInteger SHPCONST_MAIN_LIST_PRODUCT_SPONSORED_VIEW_TAG;

extern NSInteger SHPCONST_DETAIL_PRODUCT_IMAGE_VIEW_TAG;
extern NSInteger SHPCONST_DETAIL_PRODUCT_IMAGE_PROGRESS_BAR_TAG;
extern NSInteger SHPCONST_DETAIL_PRODUCT_BUTTON_LIKE;
extern NSInteger SHPCONST_DETAIL_PRODUCT_BUTTON_SHOP_TAG;
extern NSInteger SHPCONST_DETAIL_PRODUCT_DESCRIPTION_LABEL_TAG;

NSInteger SHPCONST_SHOP_DETAIL_gridViewWidth;
NSInteger SHPCONST_SHOP_DETAIL_gridViewHeight;
extern NSInteger SHPCONST_SHOP_DETAIL_gridImageWidth;
extern NSInteger SHPCONST_SHOP_DETAIL_gridImageHeight;

extern NSInteger SHPCONST_USER_ICON_WIDTH;
extern NSInteger SHPCONST_USER_ICON_HEIGHT;

extern NSString *SHPCONST_USERNAME;
extern NSString *SHPCONST_LIKE_COMMAND;
extern NSString *SHPCONST_UNLIKE_COMMAND;
extern NSString *SHPCONST_LAST_DATA_FILE_NAME;
extern NSString *SHPCONST_POST_FORM_BOUNDARY;

extern NSInteger ERROR_USERNAME_USED;
extern NSInteger ERROR_HTTP_USERNAME_USED;
extern NSInteger ERROR_HTTP_EMAIL_USED;
extern NSInteger ERROR_HTTP_USERNAME_INVALID;

extern NSInteger SHPCONST_MAX_RECENTLY_USED_SHOPS;

// add wizard
extern NSString *WIZARD_DICTIONARY_KEY;
extern NSString *WIZARD_STEP_CATEGORY_TOP_MESSAGE_KEY;
extern NSString *WIZARD_STEP_PHOTO_TOP_MESSAGE_KEY;
extern NSString *WIZARD_STEP_DESCRIPTION_TOP_MESSAGE_KEY;
extern NSString *WIZARD_STEP_TITLE_TOP_MESSAGE_KEY;
extern NSString *WIZARD_STEP_DATE_TOP_MESSAGE_KEY;
extern NSString *WIZARD_STEP_PRICE_TOP_MESSAGE_KEY;
extern NSString *WIZARD_STEP_POI_TOP_MESSAGE_KEY;

extern NSString *WIZARD_STEP_PHOTO_HINT_MESSAGE_KEY;
extern NSString *WIZARD_STEP_DESCRIPTION_HINT_MESSAGE_KEY;
extern NSString *WIZARD_STEP_TITLE_HINT_MESSAGE_KEY;
extern NSString *WIZARD_STEP_DATE_HINT_MESSAGE_KEY;
extern NSString *WIZARD_STEP_PRICE_HINT_MESSAGE_KEY;
extern NSString *WIZARD_STEP_POI_HINT_MESSAGE_KEY;

extern NSString *WIZARD_STEP_DESCRIPTION_EXAMPLE_MESSAGE_KEY;
extern NSString *WIZARD_STEP_TITLE_EXAMPLE_MESSAGE_KEY;


extern NSString *WIZARD_PRODUCT_ID_KEY;
extern NSString *WIZARD_DESCRIPTION_KEY;
extern NSString *WIZARD_TELEPHONE_KEY;
extern NSString *WIZARD_EMAIL_KEY;
extern NSString *WIZARD_TITLE_KEY;
extern NSString *WIZARD_IMAGE_KEY;
extern NSString *WIZARD_DATE_START_KEY;
extern NSString *WIZARD_DATE_END_KEY;
extern NSString *WIZARD_POI_KEY;
extern NSString *WIZARD_TYPE_KEY;
extern NSString *WIZARD_CATEGORY_KEY;
extern NSString *WIZARD_ICON_CATEGORY_KEY;
extern NSString *WIZARD_PRICE_KEY;
extern NSString *WIZARD_START_PRICE_KEY;
extern NSString *WIZARD_PERCENT_KEY;
extern NSString *WIZARD_EDIT_MODE_KEY;

extern int TAB_HOME_INDEX;
extern int TAB_SEARCH_INDEX;
//extern int TAB_NOTIFICATIONS_INDEX;
extern int TAB_MENU_INDEX;


extern int MAX_CHARACTERS_TITLE;
extern int MIN_CHARACTERS_TITLE;
extern int MIN_CHARACTERS_DESCRIPTION;

//types of category
extern NSString *CATEGORY_TYPE_DEAL;
extern NSString *CATEGORY_TYPE_COVER;
extern NSString *CATEGORY_TYPE_PHOTO;
extern NSString *CATEGORY_TYPE_EVENT;
extern NSString *CATEGORY_TYPE_MENU;

extern NSString *LAST_LOADED_CATEGORIES;
extern NSString *LAST_SELECTED_CATEGORY_KEY;
extern NSString *DICTIONARY_CATEGORIES;

@interface SHPConstants : NSObject

@end
